# Multi-stage build for Next.js + Payload CMS (production).
# Requires: next.config.ts → output: 'standalone'
#
# Stages:
#   deps    — install production deps (for runner)
#   builder — install all deps + compile the app
#   runner  — minimal image with standalone output + prod deps

FROM node:22-alpine AS base
# libc6-compat is needed for some native modules (sharp, bcrypt) on Alpine
RUN apk add --no-cache libc6-compat

# ── 1. Production deps (used in runner stage) ─────────────────────────────
FROM base AS deps
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN corepack enable pnpm && pnpm install --frozen-lockfile --prod

# ── 2. Full deps + build ──────────────────────────────────────────────────
FROM base AS builder
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN corepack enable pnpm && pnpm install --frozen-lockfile
COPY . .

# All frontend pages are force-dynamic so next build does not need a live DB.
# See src/app/(frontend)/layout.tsx for the force-dynamic export.
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
RUN corepack enable pnpm && pnpm run build

# ── 3. Minimal production image ───────────────────────────────────────────
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Static assets
COPY --from=builder /app/public ./public

# Standalone server + static chunks
RUN mkdir .next && chown nextjs:nodejs .next
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Sharp's native binary is not always picked up by Next.js file tracing when
# using pnpm. Explicitly copy the full sharp package so image processing works.
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/sharp ./node_modules/sharp

# Media volume mount point — Docker volume mapped here at runtime.
# process.cwd() inside the container is /app, so Payload writes to /app/media.
RUN mkdir -p /app/media && chown nextjs:nodejs /app/media

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# server.js is generated by next build from the standalone output
CMD ["node", "server.js"]
