import type { CollectionBeforeChangeHook } from 'payload'

/**
 * GIF animation preservation.
 *
 * Day-1 stress test (2026-04-11): uploaded a 1600×1200 3-frame animated GIF
 * via the seed script and inspected the resize variants generated by
 * Payload + Sharp 0.34.2 with the default `imageSizes` (400, 1200, 2400):
 *
 *   seed-animated.gif          → pages: 3, loop: 0, delay: [300,300,300]
 *   seed-animated-1200x900.gif → pages: 3, loop: 0, delay: [300,300,300]
 *   seed-animated-400x300.gif  → pages: 3, loop: 0, delay: [300,300,300]
 *
 * Sharp's resize pipeline DID preserve animation in all variants — the
 * concern in handoff §5.3 (resize variants flattened to a single frame)
 * does not apply with the current Sharp version. The frontend can use any
 * size variant for GIFs without losing animation.
 *
 * We still tag uploads with `isAnimatedGif: true` so frontend code can
 * make GIF-aware decisions (e.g. skip lazy-load placeholders that would
 * freeze the first frame). If a future Sharp upgrade regresses, the flag
 * also gives us a quick path to revert to "always serve original".
 */
export const handleGifUpload: CollectionBeforeChangeHook = ({ data, req }) => {
  if (!data) return data

  // The incoming upload's mimeType is on req.file (multipart) before save.
  // After save (e.g. metadata-only updates) it's on data.mimeType.
  const mimeType = (req as { file?: { mimetype?: string } }).file?.mimetype ?? data.mimeType

  return {
    ...data,
    isAnimatedGif: mimeType === 'image/gif',
  }
}
