/**
 * WordPress XML → Payload migration script (M6).
 *
 * Reads the WordPress XML export (WXR format), downloads all associated
 * images, and creates Payload Entry documents for every published post.
 *
 * Prerequisites:
 *   1. pnpm install  (xml2js is in devDependencies)
 *   2. Set DATABASE_URL and PAYLOAD_SECRET in .env
 *   3. Obtain the WP XML export from Andrea (Tools → Export → All content)
 *   4. Download the associated media files (or provide WP site access for live fetch)
 *
 * Usage:
 *   pnpm migrate -- --xml path/to/wordpress.xml [--dry-run]
 *
 * Options:
 *   --xml <path>   Path to the WordPress XML export file (required)
 *   --dry-run      Parse + summarise but do not write to the database
 *   --skip-images  Create entries without downloading images (useful for a first pass)
 *
 * What this does:
 *   1. Parses all <item> elements of type "post" (published only)
 *   2. Sorts by post_date ascending (oldest = entry #1)
 *   3. For each post, downloads attached images from WP uploads
 *   4. Uploads images via the Payload Local API (creates Media documents)
 *   5. Creates an Entry document:
 *      - entryNumber:    sequential, oldest-first
 *      - title:          <title>
 *      - slug:           auto-generated by autoSlug hook
 *      - year:           publication year (e.g. "2008")
 *      - description:    Lexical single-paragraph of stripped plaintext
 *      - plainDescription: auto-extracted by afterChange hook
 *      - images:         uploaded Media IDs, in WP gallery order
 *      - _status:        published
 *
 * Fields that need manual review after migration:
 *   - year:    only the publication year — Andrea may want to add date ranges ("2008–2010")
 *   - place:   not in WP data — fill in Payload admin
 *   - folios:  categories/tags are noted in customFields.wpCategories for reference
 *
 * Idempotency:
 *   Re-running checks for an existing entry with the same title + year before
 *   creating a duplicate. Safe to re-run if interrupted, but verify counts afterward.
 */

import 'dotenv/config'
import fs from 'node:fs'
import path from 'node:path'
import https from 'node:https'
import http from 'node:http'
import { parseStringPromise } from 'xml2js'
import { getPayload } from 'payload'

import config from '../src/payload/payload.config'

// ─── types ──────────────────────────────────────────────────────────────────

interface WpItem {
  title: string
  link: string
  pubDate: string
  'content:encoded': string
  'wp:post_id': string
  'wp:post_date': string
  'wp:post_date_gmt': string
  'wp:post_name': string
  'wp:post_type': string
  'wp:status': string
  'wp:post_parent': string
  'wp:attachment_url'?: string
  category?: Array<{ _: string; $: { domain: string; nicename: string } }>
  'wp:postmeta'?: Array<{
    'wp:meta_key': string[]
    'wp:meta_value': string[]
  }>
}

interface WpPost {
  id: string
  title: string
  slug: string
  date: Date
  htmlContent: string
  categories: string[]
  tags: string[]
  thumbnailId: string | null
  attachmentIds: string[]
}

interface WpAttachment {
  id: string
  url: string
  parentId: string
  title: string
}

// ─── helpers ─────────────────────────────────────────────────────────────────

function stripHtml(html: string): string {
  // Remove HTML tags and decode common entities
  return html
    .replace(/<[^>]+>/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#8220;/g, '\u201c')
    .replace(/&#8221;/g, '\u201d')
    .replace(/&#8217;/g, '\u2019')
    .replace(/&#8216;/g, '\u2018')
    .replace(/&#8230;/g, '\u2026')
    .replace(/&#\d+;/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim()
}

function toSingleLexicalParagraph(text: string) {
  return {
    root: {
      type: 'root',
      format: '' as const,
      indent: 0,
      version: 1,
      direction: 'ltr' as const,
      children: [
        {
          type: 'paragraph',
          format: '' as const,
          indent: 0,
          version: 1,
          direction: 'ltr' as const,
          textFormat: 0,
          textStyle: '',
          children: [
            {
              type: 'text',
              format: 0,
              mode: 'normal',
              style: '',
              text,
              detail: 0,
              version: 1,
            },
          ],
        },
      ],
    },
  }
}

function extractText<T>(val: T | T[] | undefined): string {
  if (val === undefined || val === null) return ''
  const arr = Array.isArray(val) ? val : [val]
  const first = arr[0]
  if (typeof first === 'string') return first
  if (typeof first === 'object' && first !== null && '_' in (first as object)) {
    return String((first as unknown as { _: string })._)
  }
  return String(first ?? '')
}

async function downloadToBuffer(url: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const client = url.startsWith('https') ? https : http
    client.get(url, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        const location = res.headers.location
        if (location) return downloadToBuffer(location).then(resolve).catch(reject)
        return reject(new Error(`Redirect with no Location header from ${url}`))
      }
      if (res.statusCode !== 200) {
        return reject(new Error(`HTTP ${res.statusCode} fetching ${url}`))
      }
      const chunks: Buffer[] = []
      res.on('data', (chunk: Buffer) => chunks.push(chunk))
      res.on('end', () => resolve(Buffer.concat(chunks)))
      res.on('error', reject)
    }).on('error', reject)
  })
}

function mimeTypeFromUrl(url: string): string {
  const ext = path.extname(url).toLowerCase()
  const map: Record<string, string> = {
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.png': 'image/png',
    '.gif': 'image/gif',
    '.webp': 'image/webp',
  }
  return map[ext] ?? 'image/jpeg'
}

function filenameFromUrl(url: string): string {
  return path.basename(new URL(url).pathname)
}

// ─── parse args ──────────────────────────────────────────────────────────────

const args = process.argv.slice(2)
const xmlIndex = args.indexOf('--xml')
const xmlPath = xmlIndex !== -1 ? args[xmlIndex + 1] : null
const isDryRun = args.includes('--dry-run')
const skipImages = args.includes('--skip-images')

if (!xmlPath) {
  console.error('Usage: pnpm migrate -- --xml path/to/wordpress.xml [--dry-run] [--skip-images]')
  process.exit(1)
}

if (!fs.existsSync(xmlPath)) {
  console.error(`File not found: ${xmlPath}`)
  process.exit(1)
}

// ─── main ─────────────────────────────────────────────────────────────────────

async function migrate() {
  console.log(`\n📦 alm WordPress migration`)
  console.log(`   XML:       ${xmlPath}`)
  console.log(`   Dry run:   ${isDryRun}`)
  console.log(`   Skip imgs: ${skipImages}\n`)

  // ── 1. Parse XML ────────────────────────────────────────────────────────
  console.log('1/5  Parsing XML…')
  const xml = fs.readFileSync(xmlPath!, 'utf-8')
  const parsed = await parseStringPromise(xml, { explicitArray: true })

  const channel = parsed?.rss?.channel?.[0]
  if (!channel) {
    throw new Error('Could not find <channel> in XML. Is this a valid WXR export?')
  }

  const items: WpItem[] = channel.item ?? []
  console.log(`     Found ${items.length} total items`)

  // ── 2. Separate posts from attachments ──────────────────────────────────
  console.log('2/5  Categorising items…')

  const attachments = new Map<string, WpAttachment>()
  const posts: WpPost[] = []

  for (const item of items) {
    const postType = extractText(item['wp:post_type'])
    const status = extractText(item['wp:status'])
    const id = extractText(item['wp:post_id'])

    if (postType === 'attachment') {
      const url = extractText(item['wp:attachment_url'])
      if (url) {
        attachments.set(id, {
          id,
          url,
          parentId: extractText(item['wp:post_parent']),
          title: extractText(item.title),
        })
      }
      continue
    }

    if (postType !== 'post') continue
    if (status !== 'publish') {
      console.log(`     Skipping draft/private: "${extractText(item.title)}"`)
      continue
    }

    const categories: string[] = []
    const tags: string[] = []

    for (const cat of item.category ?? []) {
      const domain = cat.$.domain
      const label = cat._
      if (domain === 'category') categories.push(label)
      else if (domain === 'post_tag') tags.push(label)
    }

    // Find the featured image ID from postmeta
    let thumbnailId: string | null = null
    for (const meta of item['wp:postmeta'] ?? []) {
      const key = extractText(meta['wp:meta_key'])
      const value = extractText(meta['wp:meta_value'])
      if (key === '_thumbnail_id' && value) {
        thumbnailId = value
      }
    }

    posts.push({
      id,
      title: extractText(item.title),
      slug: extractText(item['wp:post_name']),
      date: new Date(extractText(item['wp:post_date_gmt']) + ' UTC'),
      htmlContent: extractText(item['content:encoded']),
      categories,
      tags,
      thumbnailId,
      attachmentIds: [], // filled below
    })
  }

  // Attach all attachments to their parent post
  for (const [, attachment] of attachments) {
    const post = posts.find((p) => p.id === attachment.parentId)
    if (post) post.attachmentIds.push(attachment.id)
  }

  // Sort chronologically — oldest gets entry number 1
  posts.sort((a, b) => a.date.getTime() - b.date.getTime())

  console.log(`     Posts to migrate: ${posts.length}`)
  console.log(`     Attachments found: ${attachments.size}`)

  if (isDryRun) {
    console.log('\n── Dry run — first 10 posts ─────────────────────────────')
    for (const post of posts.slice(0, 10)) {
      const imgCount = post.attachmentIds.length
      console.log(
        `  [${String(posts.indexOf(post) + 1).padStart(3, '0')}] ` +
        `${post.date.getFullYear()}  ${post.title}  (${imgCount} images)`,
      )
    }
    console.log('\nDry run complete. Pass --xml without --dry-run to write to the database.')
    return
  }

  // ── 3. Connect to Payload ────────────────────────────────────────────────
  console.log('3/5  Connecting to Payload…')
  const payload = await getPayload({ config })
  console.log('     Connected.')

  // ── 4. Upload images & create entries ────────────────────────────────────
  console.log('4/5  Migrating entries…')

  let created = 0
  let skipped = 0
  let imagesFailed = 0

  for (let i = 0; i < posts.length; i++) {
    const post = posts[i]
    const entryNumber = i + 1
    const year = String(post.date.getFullYear())

    // Idempotency: skip if an entry with this title and year already exists
    const existing = await payload.find({
      collection: 'entries',
      where: {
        and: [
          { title: { equals: post.title } },
          { year: { equals: year } },
        ],
      },
      limit: 1,
      overrideAccess: true,
      draft: true,
    })

    if (existing.docs.length > 0) {
      console.log(`  [${String(entryNumber).padStart(3, '0')}] SKIP  "${post.title}" (${year}) — already exists`)
      skipped++
      continue
    }

    // Collect image attachments for this post
    const imageList: { url: string; title: string }[] = []

    // Featured image first (if it's a known attachment)
    if (post.thumbnailId) {
      const thumb = attachments.get(post.thumbnailId)
      if (thumb) imageList.push({ url: thumb.url, title: thumb.title })
    }

    // Remaining attachments (exclude thumbnail to avoid duplicate)
    for (const attId of post.attachmentIds) {
      if (attId === post.thumbnailId) continue
      const att = attachments.get(attId)
      if (att) imageList.push({ url: att.url, title: att.title })
    }

    // Upload images
    const uploadedImages: Array<{ image: number; caption: string }> = []

    if (!skipImages) {
      for (const img of imageList) {
        try {
          const data = await downloadToBuffer(img.url)
          const mime = mimeTypeFromUrl(img.url)
          const filename = filenameFromUrl(img.url)

          const mediaDoc = await payload.create({
            collection: 'media',
            data: { alt: img.title || post.title },
            file: { data, mimetype: mime, name: filename, size: data.length },
            overrideAccess: true,
          })
          uploadedImages.push({ image: mediaDoc.id as number, caption: img.title || '' })
        } catch (err) {
          console.warn(`     ⚠ Image fetch failed: ${img.url}  (${(err as Error).message})`)
          imagesFailed++
        }
      }
    }

    // Build description from stripped HTML
    const plainText = stripHtml(post.htmlContent)
    const description = plainText ? toSingleLexicalParagraph(plainText) : undefined

    // Create the entry as a published document (not a draft)
    await payload.create({
      collection: 'entries',
      draft: false,
      data: {
        entryNumber,
        title: post.title,
        year,
        place: '',
        description,
        images: uploadedImages,
        sortOrder: entryNumber * 10,
        _status: 'published',
        customFields: {
          wpPostId: post.id,
          wpSlug: post.slug,
          wpCategories: post.categories,
          wpTags: post.tags,
        },
      },
      overrideAccess: true,
    })

    created++
    const imgNote = skipImages ? '(images skipped)' : `${uploadedImages.length}/${imageList.length} imgs`
    console.log(`  [${String(entryNumber).padStart(3, '0')}] OK    "${post.title}" (${year}) — ${imgNote}`)
  }

  // ── 5. Summary ────────────────────────────────────────────────────────────
  console.log('\n5/5  Done.\n')
  console.log(`     Created:       ${created}`)
  console.log(`     Skipped:       ${skipped}  (already existed)`)
  console.log(`     Image errors:  ${imagesFailed}`)
  console.log(`     Total entries: ${posts.length}`)

  if (imagesFailed > 0) {
    console.log('\n⚠  Some images failed to download. Run again to retry (entries will be skipped,')
    console.log('   images will not — you will need to add them manually via the Payload admin).')
  }

  console.log('\n✅  Migration complete. Review entries at /admin/collections/entries')
  console.log('   Fields to fill in: place, year ranges, folios')
  process.exit(0)
}

migrate().catch((err) => {
  console.error('\n❌ Migration failed:', err)
  process.exit(1)
})
