/**
 * Seed script for M1 verification.
 *
 * Creates: 1 admin user, 2 folios, 5 entries (2 multi-image, 1 single-image,
 * 1 text-only, 1 with animated GIF), 4 studio pages (andrea, practice,
 * point-of-departure, contact).
 *
 * Idempotent: wipes entries/folios/media/studio-pages on each run, then
 * recreates from scratch. Safe to re-run during development.
 *
 * Run with:  pnpm seed
 */
import 'dotenv/config'
import { getPayload } from 'payload'
import sharp from 'sharp'

import config from '../src/payload/payload.config'

// ─── helpers ────────────────────────────────────────────────────────────

/** Wraps one string into a single Lexical paragraph node. */
const lexParagraph = (text: string) => ({
  type: 'paragraph',
  format: '' as const,
  indent: 0,
  version: 1,
  direction: 'ltr' as const,
  textFormat: 0,
  textStyle: '',
  children: [
    {
      type: 'text',
      format: 0,
      mode: 'normal',
      style: '',
      text,
      detail: 0,
      version: 1,
    },
  ],
})

/** Wraps a plain string in the minimal Lexical paragraph shape. */
const lex = (text: string) => ({
  root: {
    type: 'root',
    format: '' as const,
    indent: 0,
    version: 1,
    direction: 'ltr' as const,
    children: [lexParagraph(text)],
  },
})

/** Wraps multiple strings into a Lexical document — one paragraph per string. */
const lexMulti = (...paragraphs: string[]) => ({
  root: {
    type: 'root',
    format: '' as const,
    indent: 0,
    version: 1,
    direction: 'ltr' as const,
    children: paragraphs.map(lexParagraph),
  },
})

/** Solid-color PNG generated by Sharp — used for static test images. */
const makeSolidPng = async (
  width: number,
  height: number,
  color: { r: number; g: number; b: number },
): Promise<Buffer> =>
  sharp({
    create: {
      width,
      height,
      channels: 3,
      background: color,
    },
  })
    .png()
    .toBuffer()

/**
 * Generates a real 3-frame animated GIF (orange → green → blue, 200×200,
 * 300ms/frame, infinite loop) using Sharp's `join.animated` API. This is
 * the day-1 GIF preservation test from handoff §5.3.
 */
const makeAnimatedGif = async (): Promise<Buffer> => {
  // 1600×1200 — chosen so all imageSizes (400, 1200, 2400) trigger:
  //   thumbnail 400  → downscale  (will Sharp preserve animation?)
  //   medium    1200 → downscale  (will Sharp preserve animation?)
  //   large     2400 → upscale, skipped by withoutEnlargement
  // This is the actual day-1 GIF preservation stress test.
  const w = 1600
  const h = 1200
  const frames = await Promise.all(
    [
      { r: 232, g: 83, b: 30 }, // alm orange
      { r: 30, g: 200, b: 80 }, // green
      { r: 30, g: 80, b: 232 }, // blue
    ].map((color) =>
      sharp({
        create: { width: w, height: h, channels: 3, background: color },
      })
        .png()
        .toBuffer(),
    ),
  )
  return sharp(frames, { join: { animated: true } })
    .gif({ delay: [300, 300, 300], loop: 0 })
    .toBuffer()
}

/** Helper that uploads a media file via the Payload Local API. */
const uploadMedia = async (
  payload: Awaited<ReturnType<typeof getPayload>>,
  filename: string,
  mimetype: string,
  data: Buffer,
  alt: string,
) =>
  payload.create({
    collection: 'media',
    data: { alt },
    file: {
      data,
      mimetype,
      name: filename,
      size: data.length,
    },
  })

// ─── seed ───────────────────────────────────────────────────────────────

const ADMIN_EMAIL = 'admin@alm.local'
const ADMIN_PASSWORD = 'almadmin1'

async function seed() {
  // eslint-disable-next-line no-console
  console.log('🌱 seeding…')
  const payload = await getPayload({ config })

  // ── 1. wipe content collections (idempotent re-runs) ──────────────
  for (const collection of ['entries', 'folios', 'studio-pages', 'media'] as const) {
    const all = await payload.find({
      collection,
      limit: 1000,
      depth: 0,
      pagination: false,
      overrideAccess: true,
      draft: true,
    })
    for (const doc of all.docs) {
      await payload.delete({
        collection,
        id: doc.id,
        overrideAccess: true,
      })
    }
    // eslint-disable-next-line no-console
    console.log(`  ✓ wiped ${collection} (${all.docs.length})`)
  }

  // ── 2. admin user (idempotent: skip if exists) ────────────────────
  const existingAdmin = await payload.find({
    collection: 'users',
    where: { email: { equals: ADMIN_EMAIL } },
    limit: 1,
    overrideAccess: true,
  })
  if (existingAdmin.docs.length === 0) {
    await payload.create({
      collection: 'users',
      data: {
        email: ADMIN_EMAIL,
        password: ADMIN_PASSWORD,
        name: 'alm admin',
      },
      overrideAccess: true,
    })
    // eslint-disable-next-line no-console
    console.log(`  ✓ created admin user ${ADMIN_EMAIL} / ${ADMIN_PASSWORD}`)
  } else {
    // eslint-disable-next-line no-console
    console.log(`  · admin user ${ADMIN_EMAIL} already exists, skipping`)
  }

  // ── 3. folios ─────────────────────────────────────────────────────
  const architectureFolio = await payload.create({
    collection: 'folios',
    data: { name: 'Architecture', sortOrder: 1 },
    overrideAccess: true,
  })
  const identityFolio = await payload.create({
    collection: 'folios',
    data: { name: 'Identity', sortOrder: 2 },
    overrideAccess: true,
  })
  // eslint-disable-next-line no-console
  console.log('  ✓ created 2 folios')

  // ── 4. media ──────────────────────────────────────────────────────
  const imgRed = await uploadMedia(
    payload,
    'seed-red.png',
    'image/png',
    await makeSolidPng(1200, 800, { r: 232, g: 83, b: 30 }),
    'Solid orange test image',
  )
  const imgBlue = await uploadMedia(
    payload,
    'seed-blue.png',
    'image/png',
    await makeSolidPng(1200, 800, { r: 30, g: 80, b: 232 }),
    'Solid blue test image',
  )
  const imgGreen = await uploadMedia(
    payload,
    'seed-green.png',
    'image/png',
    await makeSolidPng(1200, 800, { r: 30, g: 200, b: 80 }),
    'Solid green test image',
  )
  const imgGray = await uploadMedia(
    payload,
    'seed-gray.png',
    'image/png',
    await makeSolidPng(1200, 800, { r: 136, g: 136, b: 136 }),
    'Solid gray test image',
  )
  const imgGif = await uploadMedia(
    payload,
    'seed-animated.gif',
    'image/gif',
    await makeAnimatedGif(),
    'Animated test GIF (orange → green → blue)',
  )
  // eslint-disable-next-line no-console
  console.log(`  ✓ uploaded 5 media files (gif isAnimatedGif=${(imgGif as { isAnimatedGif?: boolean }).isAnimatedGif})`)

  // ── 5. entries ────────────────────────────────────────────────────
  // Multi-image entry #1
  await payload.create({
    collection: 'entries',
    data: {
      title: 'Project Almanach 001',
      year: '2019',
      place: 'Los Angeles',
      description: lex(
        'A multi-image entry exploring color, form, and the editorial archive format. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      ),
      images: [
        { image: imgRed.id, caption: 'Frame one' },
        { image: imgBlue.id, caption: 'Frame two' },
        { image: imgGreen.id, caption: 'Frame three' },
      ],
      folios: [architectureFolio.id],
      sortOrder: 100,
      _status: 'published',
    },
    overrideAccess: true,
  })

  // Multi-image entry #2
  await payload.create({
    collection: 'entries',
    data: {
      title: 'Project Almanach 002',
      year: '2018-2020',
      place: 'Vienna',
      description: lex('Identity work and packaging study.'),
      images: [
        { image: imgGreen.id, caption: '' },
        { image: imgBlue.id, caption: '' },
      ],
      folios: [identityFolio.id],
      sortOrder: 90,
      _status: 'published',
    },
    overrideAccess: true,
  })

  // Single-image entry
  await payload.create({
    collection: 'entries',
    data: {
      title: 'Single Frame Study',
      year: '2021',
      place: 'Berlin',
      description: lex('A single-image entry. Bold and quiet.'),
      images: [{ image: imgGray.id }],
      folios: [architectureFolio.id, identityFolio.id],
      sortOrder: 80,
      _status: 'published',
    },
    overrideAccess: true,
  })

  // Text-only entry
  await payload.create({
    collection: 'entries',
    data: {
      title: 'Note on Method',
      year: '2022',
      place: '',
      description: lex(
        'A text-only entry. There are no images here. The toggle should grey out and the desktop left panel should remain blank.',
      ),
      images: [],
      sortOrder: 70,
      _status: 'published',
    },
    overrideAccess: true,
  })

  // Animated GIF entry
  await payload.create({
    collection: 'entries',
    data: {
      title: 'Motion Test',
      year: '2024',
      place: 'Studio',
      description: lex(
        'An entry containing an animated GIF. Use this to verify that frame animation is preserved end-to-end.',
      ),
      images: [{ image: imgGif.id, caption: 'Should still animate' }],
      folios: [identityFolio.id],
      sortOrder: 110,
      _status: 'published',
    },
    overrideAccess: true,
  })
  // eslint-disable-next-line no-console
  console.log('  ✓ created 5 entries')

  // ── 6. studio pages ──────────────────────────────────────────────
  const studioPages = [
    {
      pageSlug: 'andrea',
      title: 'Andrea Lenardin Madden',
      sortOrder: 1,
      content: lexMulti(
        'Lenardin\'s approach to architecture and design has been shaped by growing up and studying in Vienna, where the visual and performing arts are part of everyday discourse. A sensitivity to the layers of time and meaning that accrue to places is a hallmark of her work, joined to an equal commitment to innovation.',
        'Her education in architecture is complemented by professional studies in graphic design, product design, and fashion design. Inspired by the Renaissance architect\'s polyvalence and ability to engage every dimension of a project, Lenardin is driven by the question: can I do more, only to arrive at less?',
        'By eliciting something particular from the generic and infusing the mundane with effortless artfulness, Lenardin\'s open-ended approach enables her to devise distinctive design solutions and execute them with rigor and ingenuity.',
        'Andrea Lenardin Madden AIA',
        'Mag Arch, University of Applied Arts, Vienna | M.Arch, SCI-Arc, Los Angeles',
        'Schindler Fellow | Fulbright Scholar',
      ),
    },
    {
      pageSlug: 'practice',
      title: 'Practice',
      sortOrder: 2,
      content: lexMulti(
        'a l m project is a multidisciplinary design studio led by Andrea Lenardin Madden. The work of the studio is comprehensive in scope, touching every aspect of a project—architecture, interiors, and landscape; brand experience development, identity design, graphics and packaging; display and environmental signage systems, retail design, and digital interfaces.',
        'Each new project sets a l m on a journey. Energized as much by curiosity as by a desire to balance the elemental with the innovative, the studio begins by defining the distinctive mood that will inform a space, a building, an object, and ultimately shape its character and meaning. A collaborative process and a shared commitment to excellence ensure a final result of substance and integrity. Based in Los Angeles and Vienna, the studio works fluently across cultures and time zones.',
      ),
    },
    {
      pageSlug: 'point-of-departure',
      title: 'Point of Departure',
      sortOrder: 3,
      content: lexMulti(
        'Over the years, Andrea Lenardin Madden has built a practice at the intersection of architecture and art, with an eye toward the broader domain of placemaking. The studio\'s projects are keyed to a specific place and time, and are guided by two experiential approaches that have come to frame its thinking: instant days and future memories.',
        'Lenardin coined the term "instant days" to describe an early theoretical project that gave form to a vision of architectural practice as a holistic consideration of space and the objects it contains—one in which every aspect is imbued with both visceral and visual content that nourishes inhabitants and users.',
        'Guided by this underlying methodology, the process moves through deep analysis, strategic exploration of program, and the distillation of intrinsic elements and qualities. The result is an open-ended system in which change is embraced as an opportunity to set the stage for future memories.',
      ),
    },
    {
      pageSlug: 'contact',
      title: 'Contact',
      sortOrder: 4,
      content: lexMulti(
        'a l m project inc',
        '5544 Hollywood Boulevard, Los Angeles CA 90028',
        'Los Angeles +1 323 570 0571',
        'studio@almproject.com',
        'Vienna +43 1 581 1896',
        'atelier@almproject.com',
        'a l m Los Angeles is currently accepting internship applications.',
        'studio@almproject.com',
      ),
    },
  ]
  for (const page of studioPages) {
    await payload.create({
      collection: 'studio-pages',
      data: page,
      overrideAccess: true,
    })
  }
  // eslint-disable-next-line no-console
  console.log(`  ✓ created ${studioPages.length} studio pages`)

  // eslint-disable-next-line no-console
  console.log('🌱 done.')
  process.exit(0)
}

seed().catch((err) => {
  // eslint-disable-next-line no-console
  console.error('seed failed:', err)
  process.exit(1)
})
